CREATE TABLE IF NOT EXISTS "posts" (
    "postID" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "type" text,
    "restrict" text,
    "style" text,
    "cuteness" int,
    "thirdParty" boolean,
    "drawn" date,
    "uploaded" timestamp,
    "updated" timestamp,
    "title" text,
    "artist" text,
    "link" text,
    "commentary" text
);

CREATE TABLE IF NOT EXISTS "images" (
    "imageID" int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "postID" int REFERENCES posts ON DELETE CASCADE,
    "type" text,
    "filename" text,
    "order" int,
    "hash" text
);

CREATE TABLE IF NOT EXISTS "tags" (
    "tag" text PRIMARY KEY,
    "type" text,
    "name" text,
    "image" text,
    "description" text
);

CREATE TABLE IF NOT EXISTS "tag map" (
    "postID" int REFERENCES "posts" ON DELETE CASCADE,
    "tag" text REFERENCES "tags" ON UPDATE CASCADE
);